/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;
import Persona.Empleado;
import Persona.EmpleadoArray;


/**
 *
 * @author Jimena
 */
public class ListaAdministradores extends javax.swing.JFrame {
    
    private javax.swing.table.DefaultTableModel modeloAdmins;

    public ListaAdministradores() {
        initComponents();
        configurarTablaAdministradores();
        cargarAdministradores();
    }
     private void configurarTablaAdministradores() {
        modeloAdmins = new javax.swing.table.DefaultTableModel();
        modeloAdmins.setColumnIdentifiers(new String[]{
                "Nombre", "DNI", "Apellido Paterno", "Apellido Materno", "Cargo"
        });

        jTableAdministradores.setModel(modeloAdmins);
    }
      // ===================== CARGAR SOLO ADMINISTRADORES =====================
    private void cargarAdministradores() {
        modeloAdmins.setRowCount(0);

        for (int i = 0; i < EmpleadoArray.contador; i++) {
            Empleado emp = EmpleadoArray.empleados[i];

            if (emp.getRol().equals("Administrador")) {
                modeloAdmins.addRow(new Object[]{
                        emp.getNombre(),
                        emp.getDNI(),
                        emp.getApellidoPaterno(),
                        emp.getApellidoMaterno(),
                        emp.getRol()
                });
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAdministradores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAdministradores);

        jLabel1.setText("ADMINISTRADORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new ListaAdministradores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAdministradores;
    // End of variables declaration//GEN-END:variables
}
