/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

/**
 *
 * @author Jimena
 */
public class Menu extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    public Menu() {
        initComponents();
        accionesMenu(); // <-- ADDED
    }

    // ===================== EVENTO DEL MENÚ ===========================
   private void accionesMenu() {

    // --- Abrir formulario Empleados ---
    jMenuEmpleados.addMenuListener(new javax.swing.event.MenuListener() {
        @Override
        public void menuSelected(javax.swing.event.MenuEvent e) {
            Empleados emp = new Empleados();
            emp.setVisible(true);
            emp.setLocationRelativeTo(null);
        }
        @Override public void menuDeselected(javax.swing.event.MenuEvent e) {}
        @Override public void menuCanceled(javax.swing.event.MenuEvent e) {}
    });

    // --- Abrir formulario Lista de Administradores ---
    jMenuAdministradores.addMenuListener(new javax.swing.event.MenuListener() {
        @Override
        public void menuSelected(javax.swing.event.MenuEvent e) {
            ListaAdministradores lista = new ListaAdministradores();
            lista.setVisible(true);
            lista.setLocationRelativeTo(null);
        }
        @Override public void menuDeselected(javax.swing.event.MenuEvent e) {}
        @Override public void menuCanceled(javax.swing.event.MenuEvent e) {}
    });

    // --- Abrir formulario Clientes ---
    jMenuClientes.addMenuListener(new javax.swing.event.MenuListener() {
        @Override
        public void menuSelected(javax.swing.event.MenuEvent e) {
            Clientes cli = new Clientes();
            cli.setVisible(true);
            cli.setLocationRelativeTo(null);
        }
        @Override public void menuDeselected(javax.swing.event.MenuEvent e) {}
        @Override public void menuCanceled(javax.swing.event.MenuEvent e) {}
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuJAdministracion = new javax.swing.JMenu();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenuAdministrador = new javax.swing.JMenu();
        jMenuAdministradores = new javax.swing.JMenu();
        jMenuVehiculos = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuVendedor = new javax.swing.JMenu();
        jMenuVendedores = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenu();
        jMenuCotizacion = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU");

        jMenuInicio.setText("Inicio");
        jMenuBar1.add(jMenuInicio);

        jMenuJAdministracion.setText("J.Administración");

        jMenuEmpleados.setText("Lista de empleados");
        jMenuJAdministracion.add(jMenuEmpleados);

        jMenuBar1.add(jMenuJAdministracion);

        jMenuAdministrador.setText("Administrador");

        jMenuAdministradores.setText("Lista de administradores");
        jMenuAdministrador.add(jMenuAdministradores);

        jMenuVehiculos.setText("Vehiculos");
        jMenuAdministrador.add(jMenuVehiculos);

        jMenu3.setText("Promociones");
        jMenuAdministrador.add(jMenu3);

        jMenuBar1.add(jMenuAdministrador);

        jMenuVendedor.setText("Vendedor");

        jMenuVendedores.setText("Lista de vendedores");
        jMenuVendedor.add(jMenuVendedores);

        jMenuClientes.setText("Registro de clientes");
        jMenuVendedor.add(jMenuClientes);

        jMenuCotizacion.setText("Cotizacion");
        jMenuVendedor.add(jMenuCotizacion);

        jMenuBar1.add(jMenuVendedor);

        jMenu4.setText("Venta");
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Reporte de venta");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Salida");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAdministrador;
    private javax.swing.JMenu jMenuAdministradores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuCotizacion;
    private javax.swing.JMenu jMenuEmpleados;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenu jMenuJAdministracion;
    private javax.swing.JMenu jMenuVehiculos;
    private javax.swing.JMenu jMenuVendedor;
    private javax.swing.JMenu jMenuVendedores;
    // End of variables declaration//GEN-END:variables
}
